name: Build and Push Docker Image (arm-64))

on:
  push:
    branches: [ main ]  # Or 'master'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #runs-on: ["ARM64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: sumitsur74/github-runner:${{ vars.RUNNER_VERSION }}
          build-args: |
            RUNNER_VERSION=${{ vars.RUNNER_VERSION }}
            ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            GITHUB_REPOSITORY=${{ github.repository }}